databases:
  - name: puroka_DB
    databaseName: puroka_db
    user: puroka
    region: singapore

services:
  - type: web
    name: puroka
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: puroka_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

